### ISSUE TITLE
How do you set this up?

### ISSUE THREAD

**Issue by remotevase** [iTXTech/SynapsePM#26]
There is no wiki for set up, so  I am confused. How do you set this up? Do you still need the SynapseTransfer plugin, or does this plugin work on its own?

**Comment by jarne** [comment]
You still need the SynapseTransfer plugin to transfer players. Synapse has been extracted from the Genisys core into this plugin, so Nemisys or Synapse is the proxy server and this plugin turns a Genisys (and hopefully soon a PocketMine) server into a client of the proxy. A little bit outdated tutorial is [here](https://github.com/iTXTech/Nemisys/wiki/How-to-set-up-Nemisys), you need to set the values in the config file of this plugin instead of genisys.yml.

**Comment by remotevase** [comment]
Oh, okay, thanks!

**Comment by remotevase** [comment]
So would I have all of my synapses in the single SynapsePM File like it is here: https://github.com/remotevase/SynapsePM/blob/master/resources/config.yml
Or like it is in these:
https://github.com/remotevase/SynapsePM/blob/master/resources/FILE

**Comment by remotevase** [comment]
I think I got it, but now I get #27

**Comment by remotevase** [comment]
Oh i understand. You need to have a seperate server just for synapse
